Python tests: make sure there are no JWT tokens in logs or test output

diff --git a/.github/actions/run-python-test-set/action.yml b/.github/actions/run-python-test-set/action.yml
--- a/.github/actions/run-python-test-set/action.yml
+++ b/.github/actions/run-python-test-set/action.yml
@@ -154,6 +154,15 @@ runs:
           scripts/generate_and_push_perf_report.sh
         fi
 
+    - name: Make sure there are no sensitive data in logs
+      env:
+        TEST_OUTPUT: /tmp/test_output
+      shell: bash -euxo pipefail {0}
+      # Most of our JWT tokens start with `eyJ`
+      run: |
+          # Ensure grep of sensitive data from logs fails (configs are ok)
+          ! grep -iR eyJ $TEST_OUTPUT --include="*.log"
+
     - name: Create Allure report
       if: always()
       uses: ./.github/actions/allure-report
