Strip useless debug sections from binaries, to make them smaller.
The rust compiler or linker (I'm not sure which) emits .debug_pubnames
and .debug_pubtypes sections in the binaries. They are supposed to speed
up launching a debugger, but they're obsolete. They've been superseded
by .debug_names section in more recent DWARF spec and debuggers, and
gdb and lldb just ignores them.

I could not find any way to prevent rustc / ldb / mold from emitting
these sections in the first place. So this commit adds a hack to strip
them off afterwards. This makes the binaries about 30% smaller, for no
apparent downside.

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -168,6 +168,31 @@ jobs:
           ${cov_prefix} cargo test $CARGO_FLAGS
         shell: bash -euxo pipefail {0}
 
+      - name: Slim binaries
+        run: |
+          # Strip useless .debug_pubnames and .debug_pubtypes from all binaries.
+          # They bloat the binaries, and are not used by modern debuggers anyway.
+          # This makes the resulting binaries about 30% smaller, and also makes
+          # the cargo cache smaller.
+          #
+          # See also https://github.com/rust-lang/rust/issues/46034
+          #
+          # Note: Some files 'target' directory have hard links pointing to the
+          # same content. Files without hard links can be processed in parallel,
+          # but if you try to process the same file at the same time via two
+          # links, the two processes will conflict and faile with random "file
+          # truncated" and "file not recognized" errors. To avoid that, we
+          # first process all simple files with no hard links in parallel, and
+          # the rest one file at a time. This still processes the hard-linked
+          # files multiple times, but that's harmless as long as we don't try
+          # to run two objcopy processes at the same time.
+
+          # Process files without hard links in parallel
+          find target -executable -type f -links 1 ! -name "*.lock"  | xargs -P$(nproc) -IPATH objcopy -R .debug_pubnames -R .debug_pubtypes -p PATH
+          # Process files with hard links one at a time
+          find target -executable -type f -links +1 ! -name "*.lock"  | xargs -IPATH objcopy -R .debug_pubnames -R .debug_pubtypes -p PATH
+        shell: bash -euxo pipefail {0}
+
       - name: Install rust binaries
         run: |
           # Install target binaries
